In [13]:
import os
print(os.getcwd())

/Users/bhavika2/Desktop/Healthcare-Fraud-Intelligence/Notebooks

In [14]:
import os
print(os.listdir(".."))

['requirements.txt', 'Images', 'Models', 'README.md', 'logs', 'ai_assistant', '.gitignore', 'Dashboards', '.ipynb_checkpoints', 'data', 'Notebooks', 'Reports', 'Sql']

In [15]:
import os
print(os.listdir("../data"))

['raws', '.ipynb_checkpoints', 'processed']

In [16]:
import os
print(os.listdir("../data/raws"))

[]

In [22]:
import os

for root, dirs, files in os.walk("/Users/bhavika2/Dowmloads"):
    for file in files:
        if "MUP_PHY" in file:
            print(os.path.join(root, file))

In [25]:
import os

print(os.listdir("../data/raws"))

['MUP_PHY_R26_P05_V10_D24_Prov.csv']

In [26]:
import pandas as pd

df = pd.read_csv("../data/raws/MUP_PHY_R26_P05_V10_D24_Prov.csv")

print(df.shape)
df.head()

/var/folders/xn/c_xvmpr50hjch8d1v89j72rr0000gq/T/ipykernel_53821/2283437631.py:3: DtypeWarning: Columns (10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/raws/MUP_PHY_R26_P05_V10_D24_Prov.csv")

(1296739, 81)

,Rndrng_NPI,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_St1,Rndrng_Prvdr_St2,Rndrng_Prvdr_City,Rndrng_Prvdr_State_Abrvtn,...,Bene_CC_PH_Diabetes_V2_Pct,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre
0,1003000126,Enkeshafi,Ardalan,NaN,M.D.,I,6410 Rockledge Dr Ste 304,NaN,Bethesda,MD,...,48.0,48.0,75.0,75.0,51.0,18.0,4.0,63.0,21.0,2.5660
1,1003000134,Cibull,Thomas,L,M.D.,I,2650 Ridge Ave,Evanston Hospital,Evanston,IL,...,23.0,14.0,75.0,64.0,26.0,15.0,2.0,47.0,6.0,1.1958
2,1003000142,Khalil,Rashid,NaN,M.D.,I,4126 N Holland Sylvania Rd,Suite 220,Toledo,OH,...,45.0,27.0,75.0,75.0,36.0,17.0,NaN,75.0,11.0,1.6931
3,1003000423,Velotta,Jennifer,A,M.D.,I,8300 Tyler Blvd Ste 300,NaN,Mentor,OH,...,17.0,NaN,73.0,71.0,17.0,25.0,NaN,45.0,NaN,0.7931
4,1003000480,Rothchild,Kevin,B,MD,I,12605 E 16th Ave,NaN,Aurora,CO,...,25.0,13.0,56.0,55.0,26.0,NaN,NaN,54.0,NaN,1.4580

In [27]:
import shutil
import os

source = "/Users/bhavika2/Downloads/Medicare Physician & Other Practitioners - by Provider/2024/MUP_PHY_R26_P05_V10_D24_Prov.csv"
destination = "../data/raws/MUP_PHY_R26_P05_V10_D24_Prov.csv"

shutil.copy(source, destination)

print("Copied successfully!")

Copied successfully!

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.max_columns", None)

In [29]:
print("="*50)
print("CMS Medicare Provider Dataset")
print("="*50)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

==================================================
CMS Medicare Provider Dataset
==================================================
Rows    : 1,296,739
Columns : 81

In [30]:
df.columns

Index(['Rndrng_NPI', 'Rndrng_Prvdr_Last_Org_Name', 'Rndrng_Prvdr_First_Name',
       'Rndrng_Prvdr_MI', 'Rndrng_Prvdr_Crdntls', 'Rndrng_Prvdr_Ent_Cd',
       'Rndrng_Prvdr_St1', 'Rndrng_Prvdr_St2', 'Rndrng_Prvdr_City',
       'Rndrng_Prvdr_State_Abrvtn', 'Rndrng_Prvdr_State_FIPS',
       'Rndrng_Prvdr_Zip5', 'Rndrng_Prvdr_RUCA', 'Rndrng_Prvdr_RUCA_Desc',
       'Rndrng_Prvdr_Cntry', 'Rndrng_Prvdr_Type',
       'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 'Tot_HCPCS_Cds', 'Tot_Benes',
       'Tot_Srvcs', 'Tot_Sbmtd_Chrg', 'Tot_Mdcr_Alowd_Amt',
       'Tot_Mdcr_Pymt_Amt', 'Tot_Mdcr_Stdzd_Amt', 'Drug_Sprsn_Ind',
       'Drug_Tot_HCPCS_Cds', 'Drug_Tot_Benes', 'Drug_Tot_Srvcs',
       'Drug_Sbmtd_Chrg', 'Drug_Mdcr_Alowd_Amt', 'Drug_Mdcr_Pymt_Amt',
       'Drug_Mdcr_Stdzd_Amt', 'Med_Sprsn_Ind', 'Med_Tot_HCPCS_Cds',
       'Med_Tot_Benes', 'Med_Tot_Srvcs', 'Med_Sbmtd_Chrg',
       'Med_Mdcr_Alowd_Amt', 'Med_Mdcr_Pymt_Amt', 'Med_Mdcr_Stdzd_Amt',
       'Bene_Avg_Age', 'Bene_Age_LT_65_Cnt', 'Bene_Age_65_74_Cnt',
       'Bene_Age_75_84_Cnt', 'Bene_Age_GT_84_Cnt', 'Bene_Feml_Cnt',
       'Bene_Male_Cnt', 'Bene_Race_Wht_Cnt', 'Bene_Race_Black_Cnt',
       'Bene_Race_API_Cnt', 'Bene_Race_Hspnc_Cnt', 'Bene_Race_NatInd_Cnt',
       'Bene_Race_Othr_Cnt', 'Bene_Dual_Cnt', 'Bene_Ndual_Cnt',
       'Bene_CC_BH_ADHD_OthCD_V1_Pct', 'Bene_CC_BH_Alcohol_Drug_V1_Pct',
       'Bene_CC_BH_Tobacco_V1_Pct', 'Bene_CC_BH_Alz_NonAlzdem_V2_Pct',
       'Bene_CC_BH_Anxiety_V1_Pct', 'Bene_CC_BH_Bipolar_V1_Pct',
       'Bene_CC_BH_Mood_V2_Pct', 'Bene_CC_BH_Depress_V1_Pct',
       'Bene_CC_BH_PD_V1_Pct', 'Bene_CC_BH_PTSD_V1_Pct',
       'Bene_CC_BH_Schizo_OthPsy_V1_Pct', 'Bene_CC_PH_Asthma_V2_Pct',
       'Bene_CC_PH_Afib_V2_Pct', 'Bene_CC_PH_Cancer6_V2_Pct',
       'Bene_CC_PH_CKD_V2_Pct', 'Bene_CC_PH_COPD_V2_Pct',
       'Bene_CC_PH_Diabetes_V2_Pct', 'Bene_CC_PH_HF_NonIHD_V2_Pct',
       'Bene_CC_PH_Hyperlipidemia_V2_Pct', 'Bene_CC_PH_Hypertension_V2_Pct',
       'Bene_CC_PH_IschemicHeart_V2_Pct', 'Bene_CC_PH_Osteoporosis_V2_Pct',
       'Bene_CC_PH_Parkinson_V2_Pct', 'Bene_CC_PH_Arthritis_V2_Pct',
       'Bene_CC_PH_Stroke_TIA_V2_Pct', 'Bene_Avg_Risk_Scre'],
      dtype='object')

In [31]:
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

1. Rndrng_NPI
2. Rndrng_Prvdr_Last_Org_Name
3. Rndrng_Prvdr_First_Name
4. Rndrng_Prvdr_MI
5. Rndrng_Prvdr_Crdntls
6. Rndrng_Prvdr_Ent_Cd
7. Rndrng_Prvdr_St1
8. Rndrng_Prvdr_St2
9. Rndrng_Prvdr_City
10. Rndrng_Prvdr_State_Abrvtn
11. Rndrng_Prvdr_State_FIPS
12. Rndrng_Prvdr_Zip5
13. Rndrng_Prvdr_RUCA
14. Rndrng_Prvdr_RUCA_Desc
15. Rndrng_Prvdr_Cntry
16. Rndrng_Prvdr_Type
17. Rndrng_Prvdr_Mdcr_Prtcptg_Ind
18. Tot_HCPCS_Cds
19. Tot_Benes
20. Tot_Srvcs
21. Tot_Sbmtd_Chrg
22. Tot_Mdcr_Alowd_Amt
23. Tot_Mdcr_Pymt_Amt
24. Tot_Mdcr_Stdzd_Amt
25. Drug_Sprsn_Ind
26. Drug_Tot_HCPCS_Cds
27. Drug_Tot_Benes
28. Drug_Tot_Srvcs
29. Drug_Sbmtd_Chrg
30. Drug_Mdcr_Alowd_Amt
31. Drug_Mdcr_Pymt_Amt
32. Drug_Mdcr_Stdzd_Amt
33. Med_Sprsn_Ind
34. Med_Tot_HCPCS_Cds
35. Med_Tot_Benes
36. Med_Tot_Srvcs
37. Med_Sbmtd_Chrg
38. Med_Mdcr_Alowd_Amt
39. Med_Mdcr_Pymt_Amt
40. Med_Mdcr_Stdzd_Amt
41. Bene_Avg_Age
42. Bene_Age_LT_65_Cnt
43. Bene_Age_65_74_Cnt
44. Bene_Age_75_84_Cnt
45. Bene_Age_GT_84_Cnt
46. Bene_Feml_Cnt
47. Bene_Male_Cnt
48. Bene_Race_Wht_Cnt
49. Bene_Race_Black_Cnt
50. Bene_Race_API_Cnt
51. Bene_Race_Hspnc_Cnt
52. Bene_Race_NatInd_Cnt
53. Bene_Race_Othr_Cnt
54. Bene_Dual_Cnt
55. Bene_Ndual_Cnt
56. Bene_CC_BH_ADHD_OthCD_V1_Pct
57. Bene_CC_BH_Alcohol_Drug_V1_Pct
58. Bene_CC_BH_Tobacco_V1_Pct
59. Bene_CC_BH_Alz_NonAlzdem_V2_Pct
60. Bene_CC_BH_Anxiety_V1_Pct
61. Bene_CC_BH_Bipolar_V1_Pct
62. Bene_CC_BH_Mood_V2_Pct
63. Bene_CC_BH_Depress_V1_Pct
64. Bene_CC_BH_PD_V1_Pct
65. Bene_CC_BH_PTSD_V1_Pct
66. Bene_CC_BH_Schizo_OthPsy_V1_Pct
67. Bene_CC_PH_Asthma_V2_Pct
68. Bene_CC_PH_Afib_V2_Pct
69. Bene_CC_PH_Cancer6_V2_Pct
70. Bene_CC_PH_CKD_V2_Pct
71. Bene_CC_PH_COPD_V2_Pct
72. Bene_CC_PH_Diabetes_V2_Pct
73. Bene_CC_PH_HF_NonIHD_V2_Pct
74. Bene_CC_PH_Hyperlipidemia_V2_Pct
75. Bene_CC_PH_Hypertension_V2_Pct
76. Bene_CC_PH_IschemicHeart_V2_Pct
77. Bene_CC_PH_Osteoporosis_V2_Pct
78. Bene_CC_PH_Parkinson_V2_Pct
79. Bene_CC_PH_Arthritis_V2_Pct
80. Bene_CC_PH_Stroke_TIA_V2_Pct
81. Bene_Avg_Risk_Scre

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296739 entries, 0 to 1296738
Data columns (total 81 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   Rndrng_NPI                        1296739 non-null  int64
 1   Rndrng_Prvdr_Last_Org_Name        1296739 non-null  object
 2   Rndrng_Prvdr_First_Name           1235756 non-null  object
 3   Rndrng_Prvdr_MI                   810051 non-null   object
 4   Rndrng_Prvdr_Crdntls              1123375 non-null  object
 5   Rndrng_Prvdr_Ent_Cd               1296739 non-null  object
 6   Rndrng_Prvdr_St1                  1296739 non-null  object
 7   Rndrng_Prvdr_St2                  243316 non-null   object
 8   Rndrng_Prvdr_City                 1296739 non-null  object
 9   Rndrng_Prvdr_State_Abrvtn         1296739 non-null  object
 10  Rndrng_Prvdr_State_FIPS           1296738 non-null  object
 11  Rndrng_Prvdr_Zip5                 1296738 non-null  object
 12  Rndrng_Prvdr_RUCA                 1295902 non-null  float64
 13  Rndrng_Prvdr_RUCA_Desc            1295902 non-null  object
 14  Rndrng_Prvdr_Cntry                1296739 non-null  object
 15  Rndrng_Prvdr_Type                 1296739 non-null  object
 16  Rndrng_Prvdr_Mdcr_Prtcptg_Ind     1296739 non-null  object
 17  Tot_HCPCS_Cds                     1296739 non-null  int64
 18  Tot_Benes                         1296739 non-null  int64
 19  Tot_Srvcs                         1296739 non-null  float64
 20  Tot_Sbmtd_Chrg                    1296739 non-null  float64
 21  Tot_Mdcr_Alowd_Amt                1296739 non-null  float64
 22  Tot_Mdcr_Pymt_Amt                 1296739 non-null  float64
 23  Tot_Mdcr_Stdzd_Amt                1296739 non-null  float64
 24  Drug_Sprsn_Ind                    151696 non-null   object
 25  Drug_Tot_HCPCS_Cds                1145043 non-null  float64
 26  Drug_Tot_Benes                    1145043 non-null  float64
 27  Drug_Tot_Srvcs                    1145043 non-null  float64
 28  Drug_Sbmtd_Chrg                   1145043 non-null  float64
 29  Drug_Mdcr_Alowd_Amt               1145043 non-null  float64
 30  Drug_Mdcr_Pymt_Amt                1145043 non-null  float64
 31  Drug_Mdcr_Stdzd_Amt               1145043 non-null  float64
 32  Med_Sprsn_Ind                     151696 non-null   object
 33  Med_Tot_HCPCS_Cds                 1145043 non-null  float64
 34  Med_Tot_Benes                     1145043 non-null  float64
 35  Med_Tot_Srvcs                     1145043 non-null  float64
 36  Med_Sbmtd_Chrg                    1145043 non-null  float64
 37  Med_Mdcr_Alowd_Amt                1145043 non-null  float64
 38  Med_Mdcr_Pymt_Amt                 1145043 non-null  float64
 39  Med_Mdcr_Stdzd_Amt                1145043 non-null  float64
 40  Bene_Avg_Age                      1296739 non-null  int64
 41  Bene_Age_LT_65_Cnt                605938 non-null   float64
 42  Bene_Age_65_74_Cnt                1049599 non-null  float64
 43  Bene_Age_75_84_Cnt                928335 non-null   float64
 44  Bene_Age_GT_84_Cnt                618327 non-null   float64
 45  Bene_Feml_Cnt                     1120401 non-null  float64
 46  Bene_Male_Cnt                     1120401 non-null  float64
 47  Bene_Race_Wht_Cnt                 833987 non-null   float64
 48  Bene_Race_Black_Cnt               371840 non-null   float64
 49  Bene_Race_API_Cnt                 234199 non-null   float64
 50  Bene_Race_Hspnc_Cnt               307853 non-null   float64
 51  Bene_Race_NatInd_Cnt              447859 non-null   float64
 52  Bene_Race_Othr_Cnt                244139 non-null   float64
 53  Bene_Dual_Cnt                     832257 non-null   float64
 54  Bene_Ndual_Cnt                    832257 non-null   float64
 55  Bene_CC_BH_ADHD_OthCD_V1_Pct      421715 non-null   float64
 56  Bene_CC_BH_Alcohol_Drug_V1_Pct    669404 non-null   float64
 57  Bene_CC_BH_Tobacco_V1_Pct         774390 non-null   float64
 58  Bene_CC_BH_Alz_NonAlzdem_V2_Pct   737640 non-null   float64
 59  Bene_CC_BH_Anxiety_V1_Pct         1079901 non-null  float64
 60  Bene_CC_BH_Bipolar_V1_Pct         561408 non-null   float64
 61  Bene_CC_BH_Mood_V2_Pct            1084018 non-null  float64
 62  Bene_CC_BH_Depress_V1_Pct         1051508 non-null  float64
 63  Bene_CC_BH_PD_V1_Pct              444663 non-null   float64
 64  Bene_CC_BH_PTSD_V1_Pct            414570 non-null   float64
 65  Bene_CC_BH_Schizo_OthPsy_V1_Pct   528749 non-null   float64
 66  Bene_CC_PH_Asthma_V2_Pct          815394 non-null   float64
 67  Bene_CC_PH_Afib_V2_Pct            949666 non-null   float64
 68  Bene_CC_PH_Cancer6_V2_Pct         914441 non-null   float64
 69  Bene_CC_PH_CKD_V2_Pct             1020290 non-null  float64
 70  Bene_CC_PH_COPD_V2_Pct            922597 non-null   float64
 71  Bene_CC_PH_Diabetes_V2_Pct        1077730 non-null  float64
 72  Bene_CC_PH_HF_NonIHD_V2_Pct       929833 non-null   float64
 73  Bene_CC_PH_Hyperlipidemia_V2_Pct  1235428 non-null  float64
 74  Bene_CC_PH_Hypertension_V2_Pct    1235216 non-null  float64
 75  Bene_CC_PH_IschemicHeart_V2_Pct   1041866 non-null  float64
 76  Bene_CC_PH_Osteoporosis_V2_Pct    911907 non-null   float64
 77  Bene_CC_PH_Parkinson_V2_Pct       492452 non-null   float64
 78  Bene_CC_PH_Arthritis_V2_Pct       1169361 non-null  float64
 79  Bene_CC_PH_Stroke_TIA_V2_Pct      767032 non-null   float64
 80  Bene_Avg_Risk_Scre                1296739 non-null  float64
dtypes: float64(60), int64(4), object(17)
memory usage: 801.4+ MB

In [33]:
 df.columns

Index(['Rndrng_NPI', 'Rndrng_Prvdr_Last_Org_Name', 'Rndrng_Prvdr_First_Name',
       'Rndrng_Prvdr_MI', 'Rndrng_Prvdr_Crdntls', 'Rndrng_Prvdr_Ent_Cd',
       'Rndrng_Prvdr_St1', 'Rndrng_Prvdr_St2', 'Rndrng_Prvdr_City',
       'Rndrng_Prvdr_State_Abrvtn', 'Rndrng_Prvdr_State_FIPS',
       'Rndrng_Prvdr_Zip5', 'Rndrng_Prvdr_RUCA', 'Rndrng_Prvdr_RUCA_Desc',
       'Rndrng_Prvdr_Cntry', 'Rndrng_Prvdr_Type',
       'Rndrng_Prvdr_Mdcr_Prtcptg_Ind', 'Tot_HCPCS_Cds', 'Tot_Benes',
       'Tot_Srvcs', 'Tot_Sbmtd_Chrg', 'Tot_Mdcr_Alowd_Amt',
       'Tot_Mdcr_Pymt_Amt', 'Tot_Mdcr_Stdzd_Amt', 'Drug_Sprsn_Ind',
       'Drug_Tot_HCPCS_Cds', 'Drug_Tot_Benes', 'Drug_Tot_Srvcs',
       'Drug_Sbmtd_Chrg', 'Drug_Mdcr_Alowd_Amt', 'Drug_Mdcr_Pymt_Amt',
       'Drug_Mdcr_Stdzd_Amt', 'Med_Sprsn_Ind', 'Med_Tot_HCPCS_Cds',
       'Med_Tot_Benes', 'Med_Tot_Srvcs', 'Med_Sbmtd_Chrg',
       'Med_Mdcr_Alowd_Amt', 'Med_Mdcr_Pymt_Amt', 'Med_Mdcr_Stdzd_Amt',
       'Bene_Avg_Age', 'Bene_Age_LT_65_Cnt', 'Bene_Age_65_74_Cnt',
       'Bene_Age_75_84_Cnt', 'Bene_Age_GT_84_Cnt', 'Bene_Feml_Cnt',
       'Bene_Male_Cnt', 'Bene_Race_Wht_Cnt', 'Bene_Race_Black_Cnt',
       'Bene_Race_API_Cnt', 'Bene_Race_Hspnc_Cnt', 'Bene_Race_NatInd_Cnt',
       'Bene_Race_Othr_Cnt', 'Bene_Dual_Cnt', 'Bene_Ndual_Cnt',
       'Bene_CC_BH_ADHD_OthCD_V1_Pct', 'Bene_CC_BH_Alcohol_Drug_V1_Pct',
       'Bene_CC_BH_Tobacco_V1_Pct', 'Bene_CC_BH_Alz_NonAlzdem_V2_Pct',
       'Bene_CC_BH_Anxiety_V1_Pct', 'Bene_CC_BH_Bipolar_V1_Pct',
       'Bene_CC_BH_Mood_V2_Pct', 'Bene_CC_BH_Depress_V1_Pct',
       'Bene_CC_BH_PD_V1_Pct', 'Bene_CC_BH_PTSD_V1_Pct',
       'Bene_CC_BH_Schizo_OthPsy_V1_Pct', 'Bene_CC_PH_Asthma_V2_Pct',
       'Bene_CC_PH_Afib_V2_Pct', 'Bene_CC_PH_Cancer6_V2_Pct',
       'Bene_CC_PH_CKD_V2_Pct', 'Bene_CC_PH_COPD_V2_Pct',
       'Bene_CC_PH_Diabetes_V2_Pct', 'Bene_CC_PH_HF_NonIHD_V2_Pct',
       'Bene_CC_PH_Hyperlipidemia_V2_Pct', 'Bene_CC_PH_Hypertension_V2_Pct',
       'Bene_CC_PH_IschemicHeart_V2_Pct', 'Bene_CC_PH_Osteoporosis_V2_Pct',
       'Bene_CC_PH_Parkinson_V2_Pct', 'Bene_CC_PH_Arthritis_V2_Pct',
       'Bene_CC_PH_Stroke_TIA_V2_Pct', 'Bene_Avg_Risk_Scre'],
      dtype='object')

In [34]:
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

1. Rndrng_NPI
2. Rndrng_Prvdr_Last_Org_Name
3. Rndrng_Prvdr_First_Name
4. Rndrng_Prvdr_MI
5. Rndrng_Prvdr_Crdntls
6. Rndrng_Prvdr_Ent_Cd
7. Rndrng_Prvdr_St1
8. Rndrng_Prvdr_St2
9. Rndrng_Prvdr_City
10. Rndrng_Prvdr_State_Abrvtn
11. Rndrng_Prvdr_State_FIPS
12. Rndrng_Prvdr_Zip5
13. Rndrng_Prvdr_RUCA
14. Rndrng_Prvdr_RUCA_Desc
15. Rndrng_Prvdr_Cntry
16. Rndrng_Prvdr_Type
17. Rndrng_Prvdr_Mdcr_Prtcptg_Ind
18. Tot_HCPCS_Cds
19. Tot_Benes
20. Tot_Srvcs
21. Tot_Sbmtd_Chrg
22. Tot_Mdcr_Alowd_Amt
23. Tot_Mdcr_Pymt_Amt
24. Tot_Mdcr_Stdzd_Amt
25. Drug_Sprsn_Ind
26. Drug_Tot_HCPCS_Cds
27. Drug_Tot_Benes
28. Drug_Tot_Srvcs
29. Drug_Sbmtd_Chrg
30. Drug_Mdcr_Alowd_Amt
31. Drug_Mdcr_Pymt_Amt
32. Drug_Mdcr_Stdzd_Amt
33. Med_Sprsn_Ind
34. Med_Tot_HCPCS_Cds
35. Med_Tot_Benes
36. Med_Tot_Srvcs
37. Med_Sbmtd_Chrg
38. Med_Mdcr_Alowd_Amt
39. Med_Mdcr_Pymt_Amt
40. Med_Mdcr_Stdzd_Amt
41. Bene_Avg_Age
42. Bene_Age_LT_65_Cnt
43. Bene_Age_65_74_Cnt
44. Bene_Age_75_84_Cnt
45. Bene_Age_GT_84_Cnt
46. Bene_Feml_Cnt
47. Bene_Male_Cnt
48. Bene_Race_Wht_Cnt
49. Bene_Race_Black_Cnt
50. Bene_Race_API_Cnt
51. Bene_Race_Hspnc_Cnt
52. Bene_Race_NatInd_Cnt
53. Bene_Race_Othr_Cnt
54. Bene_Dual_Cnt
55. Bene_Ndual_Cnt
56. Bene_CC_BH_ADHD_OthCD_V1_Pct
57. Bene_CC_BH_Alcohol_Drug_V1_Pct
58. Bene_CC_BH_Tobacco_V1_Pct
59. Bene_CC_BH_Alz_NonAlzdem_V2_Pct
60. Bene_CC_BH_Anxiety_V1_Pct
61. Bene_CC_BH_Bipolar_V1_Pct
62. Bene_CC_BH_Mood_V2_Pct
63. Bene_CC_BH_Depress_V1_Pct
64. Bene_CC_BH_PD_V1_Pct
65. Bene_CC_BH_PTSD_V1_Pct
66. Bene_CC_BH_Schizo_OthPsy_V1_Pct
67. Bene_CC_PH_Asthma_V2_Pct
68. Bene_CC_PH_Afib_V2_Pct
69. Bene_CC_PH_Cancer6_V2_Pct
70. Bene_CC_PH_CKD_V2_Pct
71. Bene_CC_PH_COPD_V2_Pct
72. Bene_CC_PH_Diabetes_V2_Pct
73. Bene_CC_PH_HF_NonIHD_V2_Pct
74. Bene_CC_PH_Hyperlipidemia_V2_Pct
75. Bene_CC_PH_Hypertension_V2_Pct
76. Bene_CC_PH_IschemicHeart_V2_Pct
77. Bene_CC_PH_Osteoporosis_V2_Pct
78. Bene_CC_PH_Parkinson_V2_Pct
79. Bene_CC_PH_Arthritis_V2_Pct
80. Bene_CC_PH_Stroke_TIA_V2_Pct
81. Bene_Avg_Risk_Scre

In [35]:
df.describe()

,Rndrng_NPI,Rndrng_Prvdr_RUCA,Tot_HCPCS_Cds,Tot_Benes,Tot_Srvcs,Tot_Sbmtd_Chrg,Tot_Mdcr_Alowd_Amt,Tot_Mdcr_Pymt_Amt,Tot_Mdcr_Stdzd_Amt,Drug_Tot_HCPCS_Cds,Drug_Tot_Benes,Drug_Tot_Srvcs,Drug_Sbmtd_Chrg,Drug_Mdcr_Alowd_Amt,Drug_Mdcr_Pymt_Amt,Drug_Mdcr_Stdzd_Amt,Med_Tot_HCPCS_Cds,Med_Tot_Benes,Med_Tot_Srvcs,Med_Sbmtd_Chrg,Med_Mdcr_Alowd_Amt,Med_Mdcr_Pymt_Amt,Med_Mdcr_Stdzd_Amt,Bene_Avg_Age,Bene_Age_LT_65_Cnt,Bene_Age_65_74_Cnt,Bene_Age_75_84_Cnt,Bene_Age_GT_84_Cnt,Bene_Feml_Cnt,Bene_Male_Cnt,Bene_Race_Wht_Cnt,Bene_Race_Black_Cnt,Bene_Race_API_Cnt,Bene_Race_Hspnc_Cnt,Bene_Race_NatInd_Cnt,Bene_Race_Othr_Cnt,Bene_Dual_Cnt,Bene_Ndual_Cnt,Bene_CC_BH_ADHD_OthCD_V1_Pct,Bene_CC_BH_Alcohol_Drug_V1_Pct,Bene_CC_BH_Tobacco_V1_Pct,Bene_CC_BH_Alz_NonAlzdem_V2_Pct,Bene_CC_BH_Anxiety_V1_Pct,Bene_CC_BH_Bipolar_V1_Pct,Bene_CC_BH_Mood_V2_Pct,Bene_CC_BH_Depress_V1_Pct,Bene_CC_BH_PD_V1_Pct,Bene_CC_BH_PTSD_V1_Pct,Bene_CC_BH_Schizo_OthPsy_V1_Pct,Bene_CC_PH_Asthma_V2_Pct,Bene_CC_PH_Afib_V2_Pct,Bene_CC_PH_Cancer6_V2_Pct,Bene_CC_PH_CKD_V2_Pct,Bene_CC_PH_COPD_V2_Pct,Bene_CC_PH_Diabetes_V2_Pct,Bene_CC_PH_HF_NonIHD_V2_Pct,Bene_CC_PH_Hyperlipidemia_V2_Pct,Bene_CC_PH_Hypertension_V2_Pct,Bene_CC_PH_IschemicHeart_V2_Pct,Bene_CC_PH_Osteoporosis_V2_Pct,Bene_CC_PH_Parkinson_V2_Pct,Bene_CC_PH_Arthritis_V2_Pct,Bene_CC_PH_Stroke_TIA_V2_Pct,Bene_Avg_Risk_Scre
count,1.296739e+06,1.295902e+06,1.296739e+06,1.296739e+06,1.296739e+06,1.296739e+06,1.296739e+06,1.296739e+06,1.296739e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.145043e+06,1.296739e+06,605938.000000,1.049599e+06,928335.000000,618327.000000,1.120401e+06,1.120401e+06,8.339870e+05,371840.000000,234199.000000,307853.000000,447859.000000,244139.000000,832257.000000,8.322570e+05,421715.000000,669404.000000,774390.000000,737640.000000,1.079901e+06,561408.000000,1.084018e+06,1.051508e+06,444663.000000,414570.000000,528749.000000,815394.000000,949666.000000,914441.000000,1.020290e+06,922597.000000,1.077730e+06,929833.000000,1.235428e+06,1.235216e+06,1.041866e+06,911907.000000,492452.000000,1.169361e+06,767032.000000,1.296739e+06
mean,1.499667e+09,1.595492e+00,2.559167e+01,2.814658e+02,2.707430e+03,3.809556e+05,1.173363e+05,9.258447e+04,9.198169e+04,1.602696e+00,2.267115e+01,1.540104e+03,6.684586e+04,2.978305e+04,2.416897e+04,2.421376e+04,2.334262e+01,2.844096e+02,1.365931e+03,3.255744e+05,8.998580e+04,7.062371e+04,6.997276e+04,7.300486e+01,42.560207,1.414038e+02,134.981664,76.047092,1.822063e+02,1.385962e+02,3.277964e+02,54.222652,27.139061,45.598019,1.847206,27.329153,71.316599,3.170772e+02,1.324169,10.614081,13.005056,15.424279,3.292133e+01,8.376667,3.394430e+01,3.070139e+01,1.315342,2.304525,6.081767,12.988939,24.440802,19.562306,3.183619e+01,22.068916,3.608944e+01,25.767743,7.194136e+01,7.138696e+01,3.452164e+01,17.968860,2.474698,5.297587e+01,14.266606,1.588934e+00
std,2.878453e+08,3.256244e+00,2.791739e+01,2.678782e+03,4.563892e+04,3.336994e+06,8.490267e+05,7.698612e+05,7.622792e+05,5.565929e+00,4.757139e+02,3.541876e+04,8.361426e+05,4.373762e+05,3.529292e+05,3.535601e+05,2.680278e+01,2.843574e+03,3.251171e+04,3.399478e+06,7.503703e+05,7.110972e+05,7.017277e+05,5.037864e+00,301.173119,1.405088e+03,1083.542344,469.865748,1.667969e+03,1.215917e+03,2.658571e+03,469.693180,288.871910,376.207467,19.801386,221.888409,539.969289,2.890011e+03,4.397767,10.033412,9.236675,15.152467,1.394482e+01,10.357448,1.548517e+01,1.443450e+01,4.243130,5.909537,12.776640,5.619502,12.464837,10.816434,1.423950e+01,11.254389,1.286289e+01,15.909511,6.275454e+00,6.607488e+00,1.380936e+01,7.213232,4.797728,1.201956e+01,11.085393,8.050563e-01
min,1.003000e+09,1.000000e+00,1.000000e+00,1.100000e+01,1.100000e+01,3.169000e+01,2.640000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,2.840000e-01
25%,1.245955e+09,1.000000e+00,8.000000e+00,5.200000e+01,1.510000e+02,3.715200e+04,1.278335e+04,9.634955e+03,9.667190e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.000000e+00,5.100000e+01,1.430000e+02,3.476800e+04,1.186372e+04,9.069430e+03,9.184975e+03,7.200000e+01,16.000000,3.700000e+01,36.000000,19.000000,4.400000e+01,3.100000e+01,8.400000e+01,13.000000,0.000000,12.000000,0.000000,0.000000,17.000000,6.900000e+01,0.000000,5.000000,7.000000,5.000000,2.300000e+01,3.000000,2.300000e+01,2.000000e+01,0.000000,0.000000,0.000000,10.000000,16.000000,14.000000,2.100000e+01,14.000000,2.700000e+01,13.000000,7.200000e+01,7.000000e+01,2.400000e+01,14.000000,0.000000,4.500000e+01,7.000000,1.036600e+00
50%,1.497955e+09,1.000000e+00,1.600000e+01,1.300000e+02,4.330000e+02,1.106238e+05,3.469854e+04,2.651300e+04,2.659677e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.400000e+01,1.300000e+02,3.930000e+02,1.096510e+05,3.242276e+04,2.461227e+04,2.475417e+04,7.400000e+01,25.000000,7.200000e+01,68.000000,37.000000,8.900000e+01,6.700000e+01,1.720000e+02,25.000000,0.000000,21.000000,0.000000,17.000000,31.000000,1.540000e+02,0.000000,9.000000,12.000000,10.000000,3.000000e+01,6.000000,3.000000e+01,2.700000e+01,0.000000,0.000000,0.000000,12.000000,21.000000,17.000000,2.900000e+01,20.000000,3.400000e+01,21.000000,7.500000e+01,7.500000e+01,3.200000e+01,17.000000,0.000000,5.200000e+01,11.000000,1.355300e+00
75%,1.740940e+09,1.000000e+00,3.400000e+01,2.820000e+02,1.280000e+03,2.931786e+05,8.627380e+04,6.667240e+04,6.652660e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+01,2.810000e+02,1.068000e+03,2.836037e+05,7.995266e+04,6.094059e+04,6.072557e+04,7.500000e+01,42.000000,1.370000e+02,132.000000,75.000000,1.780000e+02,1.380000e+02,3.290000e+02,53.000000,24.000000,42.000000,0.000000,29.000000,64.000000,3.120000e+02,1.000000,14.000000,17.000000,22.000000,3.900000e+01,10.000000,4.100000e+01,3.800000e+01,1.000000,3.000000,6.000000,15.000000,32.000000,22.000000,4.100000e+01,29.000000,4.300000e+01,37.000000,7.500000e+01,7.500000e+01,4.300000e+01,21.000000,4.000000,6.100000e+01,19.000000,1.947500e+00
max,1.993000e+09,9.900000e+01,8.330000e+02,1.560327e+06,1.931950e+07,1.286033e+09,3.063578e+08,3.063578e+08,3.064470e+08,1.460000e+02,2.991280e+05,1.930842e+07,1.656163e+08,1.481929e+08,1.180699e+08,1.180699e+08,8.330000e+02,1.560327e+06,1.658793e+07,1.286033e+09,3.063578e+08,3.063578e+08,3.064470e+08,9.400000e+01,127511.000000,7.345510e+05,532764.000000,165501.000000,9.126730e+05,6.476540e+05,1.207737e+06,216104.000000,68426.000000,112251.000000,2886.000000,50948.000000,205033.000000,1.377598e+06,75.000000,75.000000,75.000000,75.000000,7.500000e+01,75.000000,7.500000e+01,7.500000e+01,75.000000,75.000000,75.000000,75.000000,75.000000,75.000000,7.500000e+01,75.000000,7.500000e+01,75.000000,7.500000e+01,7.500000e+01,7.500000e+01,75.000000,75.000000,7.500000e+01,75.000000,1.341300e+01

In [36]:
df.describe(include="object")

,Rndrng_Prvdr_Last_Org_Name,Rndrng_Prvdr_First_Name,Rndrng_Prvdr_MI,Rndrng_Prvdr_Crdntls,Rndrng_Prvdr_Ent_Cd,Rndrng_Prvdr_St1,Rndrng_Prvdr_St2,Rndrng_Prvdr_City,Rndrng_Prvdr_State_Abrvtn,Rndrng_Prvdr_State_FIPS,Rndrng_Prvdr_Zip5,Rndrng_Prvdr_RUCA_Desc,Rndrng_Prvdr_Cntry,Rndrng_Prvdr_Type,Rndrng_Prvdr_Mdcr_Prtcptg_Ind,Drug_Sprsn_Ind,Med_Sprsn_Ind
count,1296739,1235756,810051,1123375,1296739,1296739,243316,1296739,1296739,1296738,1296738,1295902,1296739,1296739,1296739,151696,151696
unique,304572,89204,32,19310,2,443330,54730,12948,62,116,34248,15,25,113,2,2,2
top,Walgreen Co,Michael,M,MD,I,200 1st St Sw,Suite 200,New York,CA,06,77030,Metropolitan area core: primary flow within an...,US,Nurse Practitioner,Y,*,#
freq,7136,20679,99490,270854,1235757,4424,6968,17708,105363,85210,5817,1099283,1296656,203212,1295719,151625,151476

In [37]:
missing = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
)

missing = missing[missing > 0]

missing

Med_Sprsn_Ind              1145043
Drug_Sprsn_Ind             1145043
Bene_Race_API_Cnt          1062540
Rndrng_Prvdr_St2           1053423
Bene_Race_Othr_Cnt         1052600
                            ...
Rndrng_Prvdr_First_Name      60983
Rndrng_Prvdr_RUCA_Desc         837
Rndrng_Prvdr_RUCA              837
Rndrng_Prvdr_State_FIPS          1
Rndrng_Prvdr_Zip5                1
Length: 63, dtype: int64

In [38]:
missing_percent = (
    df.isnull().mean() * 100
).sort_values(ascending=False)

missing_percent = missing_percent[missing_percent > 0]

missing_percent

Med_Sprsn_Ind              88.301732
Drug_Sprsn_Ind             88.301732
Bene_Race_API_Cnt          81.939388
Rndrng_Prvdr_St2           81.236317
Bene_Race_Othr_Cnt         81.172850
                             ...
Rndrng_Prvdr_First_Name     4.702797
Rndrng_Prvdr_RUCA_Desc      0.064547
Rndrng_Prvdr_RUCA           0.064547
Rndrng_Prvdr_State_FIPS     0.000077
Rndrng_Prvdr_Zip5           0.000077
Length: 63, dtype: float64

In [39]:
duplicates = df.duplicated(subset="Rndrng_NPI").sum()

print("Duplicate NPIs:", duplicates)

Duplicate NPIs: 0

In [40]:
df["Rndrng_Prvdr_State_Abrvtn"].value_counts().head(20)

Rndrng_Prvdr_State_Abrvtn
CA    105363
NY     88642
TX     86803
FL     85872
PA     63361
OH     52310
IL     51368
NC     44655
MI     43221
NJ     39694
MA     38948
GA     37050
VA     32889
TN     30048
MN     29299
WA     29103
WI     26902
AZ     26694
MD     26679
IN     26454
Name: count, dtype: int64

In [43]:
df["Rndrng_Prvdr_Type"].value_counts().head(20)

Rndrng_Prvdr_Type
Nurse Practitioner                               203212
Physician Assistant                              112514
Internal Medicine                                 93627
Family Practice                                   83639
Physical Therapist in Private Practice            77901
Certified Registered Nurse Anesthetist (CRNA)     53495
Emergency Medicine                                50101
Anesthesiology                                    41082
Diagnostic Radiology                              32843
Chiropractic                                      32394
Optometry                                         31979
Mass Immunizer Roster Biller                      26738
Obstetrics & Gynecology                           22815
Orthopedic Surgery                                21674
General Surgery                                   21065
Hospitalist                                       20529
Psychiatry                                        19778
Cardiology                                        19764
Ophthalmology                                     17519
Neurology                                         16581
Name: count, dtype: int64

In [44]:
numeric_cols = df.select_dtypes(include=np.number).columns

len(numeric_cols)

64

In [48]:
numeric_cols

Index(['Rndrng_NPI', 'Rndrng_Prvdr_RUCA', 'Tot_HCPCS_Cds', 'Tot_Benes',
       'Tot_Srvcs', 'Tot_Sbmtd_Chrg', 'Tot_Mdcr_Alowd_Amt',
       'Tot_Mdcr_Pymt_Amt', 'Tot_Mdcr_Stdzd_Amt', 'Drug_Tot_HCPCS_Cds',
       'Drug_Tot_Benes', 'Drug_Tot_Srvcs', 'Drug_Sbmtd_Chrg',
       'Drug_Mdcr_Alowd_Amt', 'Drug_Mdcr_Pymt_Amt', 'Drug_Mdcr_Stdzd_Amt',
       'Med_Tot_HCPCS_Cds', 'Med_Tot_Benes', 'Med_Tot_Srvcs', 'Med_Sbmtd_Chrg',
       'Med_Mdcr_Alowd_Amt', 'Med_Mdcr_Pymt_Amt', 'Med_Mdcr_Stdzd_Amt',
       'Bene_Avg_Age', 'Bene_Age_LT_65_Cnt', 'Bene_Age_65_74_Cnt',
       'Bene_Age_75_84_Cnt', 'Bene_Age_GT_84_Cnt', 'Bene_Feml_Cnt',
       'Bene_Male_Cnt', 'Bene_Race_Wht_Cnt', 'Bene_Race_Black_Cnt',
       'Bene_Race_API_Cnt', 'Bene_Race_Hspnc_Cnt', 'Bene_Race_NatInd_Cnt',
       'Bene_Race_Othr_Cnt', 'Bene_Dual_Cnt', 'Bene_Ndual_Cnt',
       'Bene_CC_BH_ADHD_OthCD_V1_Pct', 'Bene_CC_BH_Alcohol_Drug_V1_Pct',
       'Bene_CC_BH_Tobacco_V1_Pct', 'Bene_CC_BH_Alz_NonAlzdem_V2_Pct',
       'Bene_CC_BH_Anxiety_V1_Pct', 'Bene_CC_BH_Bipolar_V1_Pct',
       'Bene_CC_BH_Mood_V2_Pct', 'Bene_CC_BH_Depress_V1_Pct',
       'Bene_CC_BH_PD_V1_Pct', 'Bene_CC_BH_PTSD_V1_Pct',
       'Bene_CC_BH_Schizo_OthPsy_V1_Pct', 'Bene_CC_PH_Asthma_V2_Pct',
       'Bene_CC_PH_Afib_V2_Pct', 'Bene_CC_PH_Cancer6_V2_Pct',
       'Bene_CC_PH_CKD_V2_Pct', 'Bene_CC_PH_COPD_V2_Pct',
       'Bene_CC_PH_Diabetes_V2_Pct', 'Bene_CC_PH_HF_NonIHD_V2_Pct',
       'Bene_CC_PH_Hyperlipidemia_V2_Pct', 'Bene_CC_PH_Hypertension_V2_Pct',
       'Bene_CC_PH_IschemicHeart_V2_Pct', 'Bene_CC_PH_Osteoporosis_V2_Pct',
       'Bene_CC_PH_Parkinson_V2_Pct', 'Bene_CC_PH_Arthritis_V2_Pct',
       'Bene_CC_PH_Stroke_TIA_V2_Pct', 'Bene_Avg_Risk_Scre'],
      dtype='object')

In [49]:
df.memory_usage(deep=True).sum() / 1024**2

np.float64(1775.758689880371)

In [50]:
df_original = df.copy()